CREATE DATABASE likeme;

CREATE TABLE posts (id SERIAL, titulo VARCHAR(25), img VARCHAR(2500), descripcion VARCHAR(2500), likes INT);

INSERT INTO posts (titulo, img, descripcion, likes) VALUES 
('Poodle', 'https://www.mascotasalamoda.cl/wp-content/uploads/2016/11/istock_000039760954_small.jpg', 'El Poodle es una raza de perro muy conocida por su pelaje rizado y su apariencia elegante. Vienen en tres tamaños: estándar, mediano y toy. Son perros inteligentes, cariñosos y se destacan en competencias de obediencia y agilidad.', 14),
('Bulldog Ingles', 'https://cdn.shopify.com/s/files/1/0799/5301/articles/portada_ef1b4020-6028-439a-a7fe-47e54035e841.jpg?v=1657919783', 'El Bulldog Inglés es una raza de perro de tamaño mediano y cuerpo robusto. Tienen una cabeza grande y arrugada, con una expresión facial distintiva. Son conocidos por su temperamento amigable y tranquilo, y son excelentes compañeros de familia.', 0),
('Husky Siberiano', 'https://i0.wp.com/vetplace.pe/wp-content/uploads/2021/10/informacion-del-perro-siberian-husky.jpg?fit=1600%2C1068&ssl=1', 'El Husky Siberiano es una raza de perro originaria de Siberia. Tienen un pelaje denso y espeso, y vienen en una variedad de colores y patrones. Son perros muy enérgicos y necesitan mucho ejercicio y estimulación mental.', 16),
('Beagle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Beagle_Faraon.JPG/1200px-Beagle_Faraon.JPG', 'El Beagle es una raza de perro de tamaño mediano, conocida por su olfato agudo y su naturaleza amigable. Tienen orejas largas y caídas y un pelaje corto y resistente. Son perros juguetones y se llevan bien con niños y otros animales.', 11),
('Rottweiler', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/02_I_Exposici%C3%B3n_Monogr%C3%A1fica_Club_Rottweiler_de_Espa%C3%B1a_-_Santa_Brigida_-_Gran_Canaria.jpg', 'El Rottweiler es una raza de perro de gran tamaño y cuerpo musculoso. Tienen un pelaje corto y denso de color negro con marcas de fuego en el pecho y las patas. Son perros leales y protectores, y se utilizan a menudo en trabajos de seguridad y como perros de servicio.', 0),
('Xoloitzcuintli', 'https://www.thesprucepets.com/thmb/xT1SqfBbouRTMbqz8fMkpnJzGbY=/2504x0/filters:no_upscale():strip_icc()/GettyImages-1288698179-a40c40b7bb9d4b89a62187b73842050d.jpg', 'El Xoloitzcuintli, también conocido como Perro Azteca o Perro Mexicano Sin Pelo, es una raza antigua originaria de México. Se caracteriza por su falta de pelo y su piel lisa. Son perros inteligentes, leales y buenos compañeros.', 7),
('Komondor', 'https://www.dogalize.com/wp-content/uploads/2017/03/7f916ba9e0392b64b9cb5f8f39dbcbeb.jpg', 'El Komondor es una raza de perro grande y musculoso con un pelaje característico de rastas blancas. Su apariencia distintiva le ha valido el apodo de "Perro Ovejero". Son perros protectores, valientes y leales a su familia.', 0),
('Perro de Agua Portugués', 'https://mascotassaintdaniel.com/wp-content/uploads/2023/02/PT_1.jpg', 'El Perro de Agua Portugués es una raza versátil que se utiliza tradicionalmente para ayudar en la pesca y la caza en Portugal. Tienen un pelaje denso y rizado que los protege del agua fría. Son perros inteligentes, activos y amigables.', 9),
('Basenji', 'https://24943075.fs1.hubspotusercontent-eu1.net/hubfs/24943075/shutterstock_1179467188.jpg', 'El Basenji es una raza de perro originaria de África Central. Son conocidos como "Perros Cantores" debido a su habilidad para producir una serie de sonidos únicos en lugar de ladrar. Son perros inteligentes, independientes y curiosos.', 12),
('Cirneco del Etna', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCmmKNT9gsbpbo1mPH3jlOS3fKmyyV7V5PjdMmclFKcgqUFo_EJpSNmC83RmvefHuROBo&usqp=CAU', 'El Cirneco del Etna es una raza de perro de tamaño mediano originaria de Sicilia, Italia. Son perros ágiles y energéticos, criados originalmente para la caza de conejos. Tienen un pelaje corto y denso, y son conocidos por su resistencia y capacidad de trabajo.', 8),

('Cane Corso', 'https://www.akc.org/wp-content/uploads/2015/11/Cane-Corso-standing-in-the-park.jpg', 'El Cane Corso es una raza de perro italiana de gran tamaño y cuerpo musculoso. Son perros valientes y protectores, utilizados históricamente como perros de guardia y ganado. Son leales, inteligentes y requieren una socialización temprana y un entrenamiento adecuado.', 100),
('Borzoi', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Borzoi_female.jpg', 'El Borzoi, también conocido como Galgo Ruso, es una raza de perro elegante y de apariencia majestuosa. Son perros de caza rápidos y ágiles, con un pelaje largo y sedoso. Son conocidos por su temperamento suave, reservado y su amor por la carrera.', 6),
('Perro Crestado Chino', 'https://images.hola.com/imagenes/mascotas/20201116179302/perro-crestado-chino-raza-de-perro-mas-carinosa/0-889-637/crestado-juguete-a.jpg', 'El Perro Crestado Chino es una raza de perro pequeño y sin pelo, excepto por una cresta de pelo en la cabeza. Son perros juguetones, cariñosos y les encanta estar en compañía de sus dueños. Son ideales para personas alérgicas al pelo de perro.', 8),
('Dandie Dinmont Terrier', 'https://cdn.britannica.com/43/12443-050-CBA0E484/Dandie-Dinmont-terrier.jpg', 'El Dandie Dinmont Terrier es una raza de perro pequeño y de patas cortas. Tienen un pelaje duro y distintivo que les da una apariencia única. Son perros valientes, curiosos y llenos de energía. Son excelentes compañeros y se adaptan bien a la vida familiar.', 4),
('Lebrel Afgano', 'https://images.hola.com/imagenes/mascotas/20201110178930/galgo-afgano-raza-perro-mas-elegante/0-887-495/galgo-afgano-1-a.jpg', 'El Lebrel Afgano es una raza de perro de aspecto noble y elegante, conocido por su pelaje largo y sedoso. Son perros independientes, reservados y requieren espacio para correr y ejercitarse. Son excelentes cazadores y también se destacan en exposiciones caninas.', 9);






